# 基础镜像
FROM nginx
# author
MAINTAINER smarterp

# 挂载目录
VOLUME /home/smarterp/projects/smarterp-ui
# 创建目录
RUN mkdir -p /home/smarterp/projects/smarterp-ui
# 指定路径
WORKDIR /home/smarterp/projects/smarterp-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/smarterp/projects/smarterp-ui
